#!/bin/bash
PAC_DIR=/usr/local/src
HOSTS_DIR=/usr/local/hosts
SHELL_DIR=/usr/local/shell
#复制mongodb文件到服务器对应服务器上
pscp -h $HOSTS_DIR/mongo.host $PAC_DIR/mongodb* $PAC_DIR
if [ $? -ne 0 ] ;then
echo "there is an error to upload package!"
exit
 fi
echo "--- upload package success---!"
#批量安装
mussh -H $HOSTS_DIR/mongo.host -m -C $SHELL_DIR/mongodb_install

