#!/usr/bin/expect -f
set ipaddress [lindex $argv 0]
set username [lindex $argv 1]
set passwd [lindex $argv 2]
if { $argc != 3 } {
 puts stderr $passwd
 puts stderr $username
 exit 1
 }
set timeout 30
spawn ssh-copy-id -i /root/.ssh/id_rsa.pub  $username@$ipaddress
expect {
		"Are you sure you want to continue connecting (yes/no)?" {
		send "yes\r"             
		expect "password:"                 
		send "$passwd\r"             
	 }             
	#already has public key in ~/.ssh/known_hosts             
	"password:" {  
		send "$passwd\r"             
	}
    }
expect eof
